### ISSUE TITLE
Reloading the service page resulting in crashing the service

### ISSUE THREAD

**Issue by JappeHallunken** [ravenclaw900/DietPi-Dashboard#225]
When reloading the service page (calling the adress again when already on the page http://host_IP:5252/service) resulting in a crash of the dashboard service.

**Version of DietPi-Dashboard**: 0.6.0

**Nightly or stable**: Stable

**Version of DietPi**: 8.4.2

**Device architecture**: aarch64 / RPi 4

**Error log**
```
May 01 20:19:55 Dietpi dietpi-dashboard[830802]: thread 'tokio-runtime-worker' panicked at 'called ``Option::unwrap()`` on a `None`` value', src/systemdata.rs:322:55
May 01 20:19:55 Dietpi dietpi-dashboard[830802]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
May 01 20:19:55 Dietpi systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=6/ABRT
May 01 20:19:55 Dietpi systemd[1]: dietpi-dashboard.service: Failed with result 'signal'.
May 01 20:19:55 Dietpi systemd[1]: dietpi-dashboard.service: Consumed 1.133s CPU time.
```

**Comment by JappeHallunken** [comment]
The problem occurs also with nightly build v0.6.0-14-g04547aa

**Comment by ravenclaw900** [comment]
Please test the updated nightly (`v0.6.0-18-g657f5e9`).

**Comment by JappeHallunken** [comment]
It crashes now when trying to access the "Services" page.
Build v0.6.0-19-g4d6e519
```
dietpi@Dietpi:~$ sudo systemctl status dietpi-dashboard
● dietpi-dashboard.service - Web Dashboard (DietPi)
     Loaded: loaded (/etc/systemd/system/dietpi-dashboard.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/dietpi-dashboard.service.d
             └─dietpi-services_edit.conf
     Active: failed (Result: signal) since Tue 2022-05-03 17:02:57 CEST; 53s ago
    Process: 963011 ExecStart=/opt/dietpi-dashboard/dietpi-dashboard (code=killed, signal=ABRT)
   Main PID: 963011 (code=killed, signal=ABRT)
        CPU: 1.828s

May 03 17:02:51 Dietpi login[963026]: pam_unix(login:session): session opened for user root(uid=0) by (uid=0)
May 03 17:02:51 Dietpi login[963032]: ROOT LOGIN  on '/dev/pts/1'
May 03 17:02:53 Dietpi login[963026]: pam_unix(login:session): session closed for user root
May 03 17:02:53 Dietpi dietpi-dashboard[963011]: INFO  [dietpi_dashboard::socket_handlers] Closed terminal
May 03 17:02:56 Dietpi dietpi-dashboard[963011]: INFO  [dietpi_dashboard] Request to /login/
May 03 17:02:57 Dietpi dietpi-dashboard[963011]: thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/systemdata.rs:316:60
May 03 17:02:57 Dietpi dietpi-dashboard[963011]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
May 03 17:02:57 Dietpi systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=6/ABRT
May 03 17:02:57 Dietpi systemd[1]: dietpi-dashboard.service: Failed with result 'signal'.
May 03 17:02:57 Dietpi systemd[1]: dietpi-dashboard.service: Consumed 1.828s CPU time.
```

**Comment by JappeHallunken** [comment]
I was curious and tried again tonight and now I'm unable to reproduce this. The only thing I "made" was a restart of the device since yesterday.

**Comment by MichaIng** [comment]
One manual restart is required after the update. As in theory the update can be done from within the dashboard, it is not automatically restated. Does it explain your observation?

**Comment by JappeHallunken** [comment]
No, I stopped the service before triggering the update and the service got restarted automatically after the update.

**Comment by JappeHallunken** [comment]
Well I restarted the dashboard and now it's working again, idk what's going on :)

**Comment by MichaIng** [comment]
> No, I stopped the service before triggering the update and the service got restarted automatically after the update

Wow what? That shouldn't be the case. The dietpi-dashboard is explicitly not controlled, and it must not for mentioned reasons. Can you verify this, especially that it is done by `DietPi-Services` after the update/reinstall? If you, did you "include" it manually to be controlled by dietpi-services that way?

**Comment by JappeHallunken** [comment]
Looks like that's the case, but I can't recall that I changed the mode. 
I deleted the dashboard now completly and reinstalled the latest nightly (v0.6.0-26-g8dd6879) and I can confirm the default mode is "Systemd controlled" and "Included".
But now the service page is unavailable again (just nothing is loaded). When retrying to reach the page, the service crashes again.

```
May 07 14:11:35 Dietpi dietpi-dashboard[190490]: INFO  [dietpi_dashboard]
│ Request to /ws/file
│ May 07 14:12:04 Dietpi dietpi-dashboard[190490]: thread
│ 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 0 but
│ the index is 0', src/page_handlers.rs:167:41
│ May 07 14:12:04 Dietpi dietpi-dashboard[190490]: note: run with
│ `RUST_BACKTRACE=1` environment variable to display a backtrace
│ May 07 14:12:04 Dietpi systemd[1]: dietpi-dashboard.service: Main process
│ exited, code=killed, status=6/ABRT
│ May 07 14:12:04 Dietpi systemd[1]: dietpi-dashboard.service: Failed with
│ result 'signal'.
│ May 07 14:12:04 Dietpi systemd[1]: dietpi-dashboard.service: Consumed 2.108s
│ CPU time.

```

**Comment by JappeHallunken** [comment]
To solve this problem I restarted the device. Restarting the service was not a solution.

**Comment by MichaIng** [comment]
> and I can confirm the default mode is "Systemd controlled" and "Included".

Can you please paste the output of those commands:
```sh
systemctl status dietpi-dasbboard
cat /boot/dietpi/.dietpi-services_include_exclude
```

**Comment by JappeHallunken** [comment]
```
sudo systemctl status dietpi-dashboard
● dietpi-dashboard.service - Web Dashboard (DietPi)
     Loaded: loaded (/etc/systemd/system/dietpi-dashboard.service; enabled; vend                                              or preset: enabled)
     Active: active (running) since Sat 2022-05-07 14:13:35 CEST; 9h ago
   Main PID: 605 (dietpi-dashboar)
      Tasks: 5 (limit: 4446)
        CPU: 4.210s
     CGroup: /system.slice/dietpi-dashboard.service
             └─605 /opt/dietpi-dashboard/dietpi-dashboard

May 07 14:13:35 Dietpi dietpi-dashboard[605]: INFO  [warp::server] listening on                                               http://[::]:5252
May 07 14:31:55 Dietpi dietpi-dashboard[605]: INFO  [dietpi_dashboard] Request t                                              o /
May 07 14:31:55 Dietpi dietpi-dashboard[605]: INFO  [dietpi_dashboard] Request t                                              o /assets/index.1d66b0c4.js
May 07 14:31:55 Dietpi dietpi-dashboard[605]: INFO  [dietpi_dashboard] Request t                                              o /assets/index.f0f349df.css
May 07 14:31:55 Dietpi dietpi-dashboard[605]: INFO  [dietpi_dashboard] Request t                                              o /assets/xterm.98e358f6.js
May 07 14:31:55 Dietpi dietpi-dashboard[605]: INFO  [dietpi_dashboard] Request t                                              o /assets/xterm.98e358f6.js
May 07 14:31:55 Dietpi dietpi-dashboard[605]: INFO  [dietpi_dashboard] Request t                                              o /assets/github-mark.31287333.svg
May 07 14:31:55 Dietpi dietpi-dashboard[605]: INFO  [dietpi_dashboard] Request t                                              o /ws
May 07 14:31:55 Dietpi dietpi-dashboard[605]: INFO  [dietpi_dashboard] Request t                                              o /assets/dietpi.4cc58251.png
May 07 14:31:55 Dietpi dietpi-dashboard[605]: INFO  [dietpi_dashboard] Request t                                              o /favicon.png
```
```
 cat /boot/dietpi/.dietpi-services_include_exclude

- transmission-daemon

- proftpd
- papermc
```

**Comment by MichaIng** [comment]
Ah, I see `dietpi-services` does not show the "controlled"/"included" status correctly for those services, which are known OOTB, e.g. listed in the menu and shown by `dietpi-services status`, but explicitly/intentionally not stopped/started.

Based on your outputs, the dashboard services is not stopped or restarted on `dietpi-software` installs. You see it at the beginning and at the end of installs/reinstalls. But it is enabled and "started" at the end of installs/reinstalls. This however has no effect if it is running already. This aims to have a running service at the end of first/fresh dashboard installs, but it is not aimed to restart it to have the update take effect. You should see the service being enabled and started after the following line at the end of installs/reinstalls:
```sh
[ INFO ] Starting installed services, not controlled by DietPi-Services
```

**Comment by ravenclaw900** [comment]
The crashing problem is being worked on in #236. My guess is that something was malformed with the DietPi-Services output, and restarting fixed that.
