### ISSUE TITLE
dietpi-dashbard crashed itself

### ISSUE THREAD

**Issue by id4vip** [ravenclaw900/DietPi-Dashboard#37]
I installed dietpi dashboard on my raspberry pi-B2 & intel nuc both devices yesterday night. after running some time correctly on both devices. this app itself killed & the log file show this type of error

```
Nov 13 18:14:43 DietPi dietpi-dashboard[409]: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Protocol("Connection reset without closing handshake")', src/sockets.rs:295:58
Nov 13 18:14:43 DietPi dietpi-dashboard[409]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 13 18:14:43 DietPi systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=6/ABRT
Nov 13 18:14:43 DietPi systemd[1]: dietpi-dashboard.service: Failed with result 'signal'.
Nov 13 18:14:43 DietPi systemd[1]: dietpi-dashboard.service: Consumed 4.519s CPU time.
```

after restart dietpi-dashboard it is again start & start running. so i do not have any idea why this app killed by both dietpi systems.
& in another device the error log is like this

```
Nov 13 17:34:12 DietPi dietpi-dashboard[41875]: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })', src/sockets.rs:295:58
Nov 13 17:34:12 DietPi dietpi-dashboard[41875]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 13 17:34:12 DietPi systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=6/ABRT
Nov 13 17:34:12 DietPi systemd[1]: dietpi-dashboard.service: Failed with result 'signal'.
Nov 13 17:34:12 DietPi systemd[1]: dietpi-dashboard.service: Consumed 13.059s CPU time.
```

**Comment by ravenclaw900** [comment]
Indeed, you'll get this error if the browser connected to the dashboard shuts down without trying to close the connection. I'll have close on an 'error' like that as well.

**Comment by ravenclaw900** [comment]
Fixed with: https://github.com/ravenclaw900/DietPi-Dashboard/commit/630d38d6dab2dbd90f458f4905bb66dc440493d4. Please test the latest nightly.

**Comment by Mister-XY** [comment]
I use the nightly and have the same error.
```
Nov 17 03:21:38 DietPi-RPI3MA dietpi-dashboard[13273]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 17 03:21:38 DietPi-RPI3MA systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=6/ABRT
Nov 17 03:21:38 DietPi-RPI3MA systemd[1]: dietpi-dashboard.service: Failed with result 'signal'.
Nov 17 03:21:38 DietPi-RPI3MA systemd[1]: dietpi-dashboard.service: Consumed 5.947s CPU time.
root@DietPi-RPI3MA:~# systemctl status dietpi-dashboard
● dietpi-dashboard.service - Web Dashboard (DietPi)
     Loaded: loaded (/etc/systemd/system/dietpi-dashboard.service; enabled; vendor preset: enabled)
     Active: failed (Result: signal) since Wed 2021-11-17 03:21:38 CET; 1 day 11h ago
   Main PID: 13273 (code=killed, signal=ABRT)
        CPU: 5.947s
```

**Comment by ravenclaw900** [comment]
Hello,
Please post `journalctl -u dietpi-dashboard`.

**Comment by Mister-XY** [comment]
```
root@DietPi-RPI3MA:~# journalctl -u dietpi-dashboard
Journal file /var/log/journal/f1da8829603a4a059931b4e7232c1e3f/system.journal is truncated, ignoring file.
-- Journal begins at Mon 2021-11-15 11:23:50 CET, ends at Thu 2021-11-18 17:12:37 CET. --
Nov 15 18:54:20 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-15 18:54:20,934 INFO  [dietpi_dashboard] Request to /
Nov 15 18:54:21 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-15 18:54:21,006 INFO  [dietpi_dashboard] Request to /assets/index.30c27941.css
Nov 15 18:54:21 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-15 18:54:21,015 INFO  [dietpi_dashboard] Request to /assets/index.d1f207ca.js
Nov 15 18:54:21 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-15 18:54:21,155 INFO  [dietpi_dashboard] Request to /assets/xterm.39cfe26b.js
Nov 15 18:54:21 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-15 18:54:21,266 INFO  [dietpi_dashboard] Request to /assets/xterm.39cfe26b.js
Nov 15 18:54:21 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-15 18:54:21,273 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Nov 15 18:54:21 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-15 18:54:21,279 INFO  [dietpi_dashboard] Request to /ws
Nov 15 18:54:21 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-15 18:54:21,357 INFO  [dietpi_dashboard] Request to /favicon.png
Nov 16 08:17:05 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-16 08:17:05,980 INFO  [dietpi_dashboard] Request to /
Nov 16 08:17:06 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-16 08:17:06,041 INFO  [dietpi_dashboard] Request to /assets/index.d1f207ca.js
Nov 16 08:17:06 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-16 08:17:06,048 INFO  [dietpi_dashboard] Request to /assets/index.30c27941.css
Nov 16 08:17:06 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-16 08:17:06,190 INFO  [dietpi_dashboard] Request to /assets/xterm.39cfe26b.js
Nov 16 08:17:06 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-16 08:17:06,297 INFO  [dietpi_dashboard] Request to /assets/xterm.39cfe26b.js
Nov 16 08:17:06 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-16 08:17:06,300 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Nov 16 08:17:06 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-16 08:17:06,305 INFO  [dietpi_dashboard] Request to /ws
Nov 16 08:17:06 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-16 08:17:06,391 INFO  [dietpi_dashboard] Request to /favicon.png
Nov 17 03:18:53 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-17 03:18:53,232 INFO  [dietpi_dashboard] Request to /
Nov 17 03:18:53 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-17 03:18:53,309 INFO  [dietpi_dashboard] Request to /assets/index.d1f207ca.js
Nov 17 03:18:53 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-17 03:18:53,316 INFO  [dietpi_dashboard] Request to /assets/index.30c27941.css
Nov 17 03:18:53 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-17 03:18:53,470 INFO  [dietpi_dashboard] Request to /assets/xterm.39cfe26b.js
Nov 17 03:18:53 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-17 03:18:53,594 INFO  [dietpi_dashboard] Request to /assets/xterm.39cfe26b.js
Nov 17 03:18:53 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-17 03:18:53,599 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Nov 17 03:18:53 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-17 03:18:53,608 INFO  [dietpi_dashboard] Request to /ws
Nov 17 03:18:53 DietPi-RPI3MA dietpi-dashboard[13273]: 2021-11-17 03:18:53,683 INFO  [dietpi_dashboard] Request to /favicon.png
Nov 17 03:21:38 DietPi-RPI3MA dietpi-dashboard[13273]: thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/sockets.rs:294:58
Nov 17 03:21:38 DietPi-RPI3MA dietpi-dashboard[13273]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 17 03:21:38 DietPi-RPI3MA systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=6/ABRT
Nov 17 03:21:38 DietPi-RPI3MA systemd[1]: dietpi-dashboard.service: Failed with result 'signal'.
Nov 17 03:21:38 DietPi-RPI3MA systemd[1]: dietpi-dashboard.service: Consumed 5.947s CPU time.
Nov 18 14:42:40 DietPi-RPI3MA systemd[1]: Started Web Dashboard (DietPi).
Nov 18 14:42:40 DietPi-RPI3MA dietpi-dashboard[28162]: 2021-11-18 14:42:40,568 INFO  [warp::server] Server::run; addr=0.0.0.0:8088
Nov 18 14:42:40 DietPi-RPI3MA dietpi-dashboard[28162]: 2021-11-18 14:42:40,569 INFO  [warp::server] listening on http://0.0.0.0:8088
Nov 18 14:42:44 DietPi-RPI3MA dietpi-dashboard[28162]: 2021-11-18 14:42:44,240 INFO  [dietpi_dashboard] Request to /
Nov 18 14:42:44 DietPi-RPI3MA dietpi-dashboard[28162]: 2021-11-18 14:42:44,285 INFO  [dietpi_dashboard] Request to /assets/index.8e45996a.js
Nov 18 14:42:44 DietPi-RPI3MA dietpi-dashboard[28162]: 2021-11-18 14:42:44,288 INFO  [dietpi_dashboard] Request to /assets/index.30c27941.css
Nov 18 14:42:44 DietPi-RPI3MA dietpi-dashboard[28162]: 2021-11-18 14:42:44,473 INFO  [dietpi_dashboard] Request to /assets/xterm.39cfe26b.js
Nov 18 14:42:44 DietPi-RPI3MA dietpi-dashboard[28162]: 2021-11-18 14:42:44,610 INFO  [dietpi_dashboard] Request to /assets/xterm.39cfe26b.js
Nov 18 14:42:44 DietPi-RPI3MA dietpi-dashboard[28162]: 2021-11-18 14:42:44,618 INFO  [dietpi_dashboard] Request to /assets/dietpi.4cc58251.png
Nov 18 14:42:44 DietPi-RPI3MA dietpi-dashboard[28162]: 2021-11-18 14:42:44,620 INFO  [dietpi_dashboard] Request to /ws
Nov 18 14:42:44 DietPi-RPI3MA dietpi-dashboard[28162]: 2021-11-18 14:42:44,717 INFO  [dietpi_dashboard] Request to /favicon.png
```

**Comment by ravenclaw900** [comment]
It looks like the messages being sent back and forth were not able to be turned into text. Do you remember what page you were on when that happened? Was it the terminal?

**Comment by Mister-XY** [comment]
I have no idea, because, the dashboard runs 2 days very good.

**Comment by ravenclaw900** [comment]
@id4vip, can this be closed?
@Mister-XY, if you're still having problems, feel free to open a new issue.

**Comment by Mister-XY** [comment]
It's also crashed
